title: Will Roper
#logo:
description: I'm fascinated with the evolution of software, the global computing infrastructure, and the industries and companies that build them. In recent years, I've used my journalism experience to write and edit stories with leading cloud observability and telecommunications companies. 
#show_downloads: false
theme: jekyll-theme-minimal
