title: Will Roper
#logo:
description: "Technical editor and writer specializing in cloud infrastructure, observability, and developer tooling.<br><br><a href=\"https://www.linkedin.com/in/willemroper\">LinkedIn</a>"
#show_downloads: false
theme: jekyll-theme-minimal
