title: Will Roper
#logo:
description: I'm fascinated with the evolution of software and global computing infrastructure. In recent years, I've used my journalism experience to write and edit stories with leading companies that build these spaces, including in cloud observability and telecommunications. 
#show_downloads: false
theme: jekyll-theme-minimal
